### ISSUE TITLE
Finish Blender advanced verification PR

### ISSUE THREAD

**Issue by ggruszczynski** [golemfactory/golem-verificator#10]
In golem_core there is experimental Blender advanced verification PR: golemfactory/golem#1656
The PR must be cleaned and merged. My personal WIP checks are marked as 
`#golem_verificator todo`.

It uses the golem_verificator package. 
Take care of 
`def test_blender_real_task_png_should_pass(self):` and 
`test_blender_real_task_png_should_fail`
from golemfactory/golem#1656 
These tests the full verification workflow for blender.

**Comment by Elfoniok** [comment]
Before these PR can be merged either golem-core need to depends on blender package. Or verificator will be modified to use blender in docker machine from available images.
