### ISSUE TITLE
Choose scenes for tests

### ISSUE THREAD

**Issue by magdasta** [golemfactory/golem-verificator#21]
We'd like to have around 20-30 scenes which we will render with various sampling, resolution and output format. Please take a look at the scenes we have and choose maximally diverse subset of them.

**Comment by badb** [comment]
Can we use set off scenes that was already defined before by @ederenn and @Elfoniok?

**Comment by magdasta** [comment]
We can use some of them, but 1) I think we should have more scenes carefully analyzed, standardized, and 2) I think it's a good idea to reevaluate the choosing, it won't hurt us much to think about it again - and it might be absolutely crucial for proper tuning of the (final) verification parameters (whatever they'll turn to be)
