### ISSUE TITLE
replace base docker img with a ligher one

### ISSUE THREAD

**Issue by ggruszczynski** [golemfactory/golem-verificator#4]
It turned out, that current docker img_metrics `FROM python:3.6` is very heavy (1.46GB)

Golems' images `FROM golemfactory/base:1.2` do not have python3 and there is no obvious way to install it.

maybe one of these will luckily work:
https://hub.docker.com/_/python/

**Comment by badb** [comment]
Good candiate: https://revsys.com/tidbits/optimized-python/

**Comment by Elfoniok** [comment]
Well i tried with custom image builded on debian:stretch images which yields 1,14Gb size.
So i tried optimized-python as badb suggested which yielded 1,1Mb
What really done the trick wast to remove build dependency for openEXR, now openEXR wheel is downloaded from our wheel server, so there is no need for gcc and build dependencies on container.
Current size is 889MB.
